BarendoSystems/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CAuthentication.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include("allauth.urls")),
    path('payment/', include('payment.urls')),
    path('paypal/', include('paypal.standard.ipn.urls'))
]

# serving static files in development
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name='cart_home'),
    path('cart_add/', views.add_item, name='add_item'),
    path('remove_item/', views.remove_item, name='remove_item'),
    path('update_cart/', views.update_cart, name='update_cart'),
]

order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('', views.order_page, name='order_page'),
    path('update_address/', views.update_address, name='update_address'),
    path('update_payment_details/', views.update_payment_details, name='update_payment_details'),
    path('payment/', views.payment_processing, name='payment_processing'),
    path('pre-paid-pending-orders/', views.pre_paid_pending_orders, name="pre-paid-pending-orders"),
    path('pay-on-delivery-pending-orders/', views.pay_on_delivery_pending_orders, name="pay-on-delivery-pending-orders"),
    path('order/<int:order_id>', views.specific_order, name="specific-order"),
    path('cancel-order/<int:order_id>', views.cancel_order, name="cancel-order"),
    path('shipped/', views.shipped_orders, name="shipped-orders"),
    path('cancelled/', views.cancelled_orders, name="cancelled-orders"),
]

order/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from django.conf import settings
from django.utils import timezone

from store.models import Product


class Order(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
    ]

    PAYMENT_DATE_CHOICES = [
        ('now', 'Pay now'),
        ('on_delivery', 'Pay upon delivery'),
    ]

    PAYMENT_METHOD_CHOICES = [
        ('mpesa', 'Mpesa'),
        ('paypal', 'Paypal'),
        ('credit/debit', 'Credit/debit card'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    town = models.CharField(max_length=100, blank=True, null=True)
    products = models.ManyToManyField(Product, through='OrderItem')
    created_date = models.DateTimeField(default=timezone.now)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    shipped = models.BooleanField(null=True, blank=True, default=False )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')

    shipped_date = models.DateTimeField(null=True, blank=True)
    delivered_date = models.DateTimeField(null=True, blank=True)
    cancelled_date = models.DateTimeField(null=True, blank=True)
    receipt_number = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    # New fields for payment
    payment_date = models.CharField(max_length=20)
    payment_method = models.CharField(max_length=20)

    def update_status(self, new_status):
        if new_status in dict(self.STATUS_CHOICES):
            self.status = new_status
            # Automatically set the corresponding date field based on the new status
            if new_status == 'Shipped':
                self.shipped_date = timezone.now()
            elif new_status == 'Delivered':
                self.delivered_date = timezone.now()
            elif new_status == 'Cancelled':
                self.cancelled_date = timezone.now()
            # Save changes to the database
            self.save()
        else:
            raise ValueError("Invalid status")

    def update_total_cost(self, total_cost):
        self.total_price = total_cost
        self.save()

    def save(self, *args, **kwargs):
        # Populate phone, address, and town from the user's profile if they exist
        if not self.phone or not self.address or not self.town:
            profile = getattr(self.user, 'profile', None)
            if profile:
                self.phone = profile.phone
                self.address = profile.address
                self.town = profile.town
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Order #{self.id} by {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

order/views.py
from django.contrib import messages
from django.http import HttpResponse
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from CAuthentication.forms import UpdateProfile
from CAuthentication.models import Profile
from cart.cart import Cart
from order.models import Order, OrderItem
from store.models import Product
from django.http import HttpResponse


# Create your views here.
def order_page(request):
    user = request.user
    if user.is_authenticated:
        profile = Profile.objects.get(user__id=user.id)
        if profile.old_cart != "{}":
            if not profile.phone or not profile.town or not profile.address:
                profile_complete = False
            else:
                profile_complete = True
            payment_date = request.session.get('paymentDate')
            payment_method = request.session.get('paymentMethod')
            if payment_date and payment_method:
                payment_details_complete = True
            else:
                payment_details_complete = False
            cart = Cart(request)
            products = Product.objects.filter(id__in=cart.cart_summary().keys())
            context = {
                'products': products,
                'products_cost': cart.total_cost(),
                'cart': cart.cart_summary(),
                'profile': profile,
                'profile_complete': profile_complete,
                'paymentDate': payment_date,
                'paymentMethod': payment_method,
                'payment_complete': payment_details_complete,
            }
            return render(request, 'order/checkout.html', context)
        else:
            messages.warning(request, "You have to have something in your cart to access this page!")
            return redirect('CAuthentication:home')
    else:
        messages.warning(request, "You have to be authenticated to access this page!")
        return redirect('CAuthentication:home')


def update_address(request):
    profile = Profile.objects.get(user__id=request.user.id)
    profile_form = UpdateProfile(request.POST or None, instance=profile)
    if profile_form.is_valid():
        profile_form.save()
        return redirect('order:order_page')
    else:
        return render(request, 'order/Address.html', {'address_form': profile_form})


def update_payment_details(request):
    if request.method == 'POST':
        PAYMENT_DATE_CHOICES = {
            "now": 'Pay now',
            "on_delivery": 'Pay upon delivery'
        }


        # Get selected values from the POST data
        request.session['paymentDate'] = request.POST.get('paymentDate')
        request.session['paymentMethod'] = request.POST.get('paymentMethod')


        # Mark the session as modified to save changes
        request.session.modified = True

        # Debug print to check session values
        print(request.session.values())
        return redirect('order:order_page')

    return render(request, 'order/Payment Details.html', {})



def payment_processing(request):
    # Access the cart and create a new order
    cart = Cart(request)
    new_order = Order(
        user=request.user,
        total_price=cart.total_cost(),
        payment_date=request.session.get('paymentDate'),
        payment_method=request.session.get('paymentMethod')
    )
    print(f"{new_order.total_price}")
    

    new_order.save()

    # Get cart summary and products in one query
    cart_summary = cart.cart_summary()
    product_ids = cart_summary.keys()
    products = Product.objects.filter(id__in=product_ids)

    # Create OrderItems in bulk
    order_items = []
    for product in products:
        # Retrieve quantity and price directly from cart summary
        item_data = cart_summary.get(str(product.id))
        if item_data:
            order_items.append(OrderItem(
                order=new_order,
                product=product,
                quantity=item_data['quantity'],
                price=item_data['price']
            ))

    # Save all OrderItems at once
    OrderItem.objects.bulk_create(order_items)
    cart.empty_cart()
    return redirect(reverse('payment:paypal', kwargs={'order_id': new_order.id}))

def pre_paid_pending_orders(request):
    orders = Order.objects.filter(payment_date="Pay now", status="Pending")
    context = {
        "orders": orders
    }
    return render(request, "order/pre-paid-pending-orders.html", context)

def pay_on_delivery_pending_orders(request):
    orders = Order.objects.filter(payment_date="Pay upon delivery", status="Pending")
    context = {
        "orders": orders
    }
    return render(request, "order/pay-on-delivery-pending-orders.html", context)

def specific_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    orderItems = OrderItem.objects.filter(order__id=order_id)

    if request.method == 'POST':
        order = get_object_or_404(Order, id=order_id)
        order.shipped = True
        order.status = "Shipped"
        order.shipped_date = datetime.datetime.now()
        order.save()
        return redirect("CAuthentication:home")

    return render(request, "order/order.html", {"order": order, "order_items": orderItems})


def shipped_orders(request):
    orders = Order.objects.filter(status="Shipped")
    return render(request, "order/shipped-orders.html", {"orders":orders})

def cancel_order(request, order_id):
    if request.method == 'POST':
        order = get_object_or_404(Order, id=order_id)
        order.status = "Cancelled"
        order.cancelled_date = datetime.datetime.now()
        order.save()
        return redirect("CAuthentication:home")
    else: 
        return redirect("store:store")

def cancelled_orders(request):
    orders = Order.objects.filter(status="Cancelled")
    return render(request, "order/Cancelled-orders.html", {"orders":orders})

templates/order/Payment Details.html
{% extends 'common/base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}
    Change your Payment Details | Barendo Systems
{% endblock %}
{% block content %}

    <div style="background-color: #f4f4f4">
        <br>
        <div class="row mx-3 mx-sm-4 mx-md-5 pb-4">
            <div class="container col-md-8 col-12 order-md-1 order-2 mt-4 mt-md-0">
                <div class="container w-100 shadowed-div"
                     style="margin-inline-end: 1%; background-color: white; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                    <div class="pt-3 ps-3 d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="bi bi-check-circle-fill" style="color: grey; margin-right: 8px;"></i>
                            <h6 class="mb-0">1. Customer Address</h6>
                        </div>
                    </div>
                    <hr style="margin: 5px 0 15px 0;">
                </div>
                <div class="container w-100 shadowed-div"
                     style="margin-inline-end: 1%; background-color: white; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                    <div class="pt-3 ps-3 d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="bi bi-check-circle-fill" style="color: green; margin-right: 8px;"></i>
                            <h6 class="mb-0">2. Delivery Details</h6>
                        </div>
                        <a href="" class="text-decoration-none" style="color: #3bc9fd"></a>
                    </div>
                    <hr style="margin: 5px 0 15px 0;">
                </div>

                <div class="container w-100 shadowed-div"
                     style="margin-inline-end: 1%; background-color: white; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                    <div class="pt-3 ps-3 d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="bi bi-check-circle-fill" style="color: green; margin-right: 8px;"></i>
                            <h6 class="mb-0">3. Payment Details</h6>
                        </div>
                    </div>
                    <hr style="margin: 2px 0 5px 0;">
                    <div class="row px-2 align-items-center">
                        <div class="payment-options p-3 rounded" style="">
                            <form action="{% url 'order:update_payment_details' %}" method="post" onsubmit="return validateForm()" id="radioForm">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 col-12">

                                        <h5>Select Payment Date</h5>
                                        <div class="form-check mt-2">
                                            <input type="radio" class="form-check-input" name="paymentDate" value="Pay now">
                                            <label class="form-check-label" for="payNowRadio" >Pay Now</label>
                                        </div>
                                        <div class="form-check mt-2">
                                            <input type="radio" class="form-check-input" name="paymentDate" value="Pay upon delivery">
                                            <label class="form-check-label" for="payOnDeliveryRadio">Pay on
                                                Delivery</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div id="additionalPaymentOptions" class="mt-2">
                                            <h5>Choose Payment Method</h5>
                                            <div class="form-check mt-2 d-flex align-items-center">
                                                <input type="radio" class="form-check-input" name="paymentMethod"
                                                       id="paypalRadio" value="Paypal">&nbsp;&nbsp;
                                                <label class="form-check-label" for="paypalRadio">PayPal</label> &nbsp;&nbsp;&nbsp;
                                                <img src="{% static 'svg/paypal-svgrepo-com.svg' %}" alt=""
                                                     style="height: 40px ;">
                                            </div>
                                            <div class="form-check mt-2 d-flex align-items-center">
                                                <input type="radio" class="form-check-input" name="paymentMethod"
                                                       id="mpesaRadio" value="Mpesa">&nbsp;&nbsp;
                                                <label class="form-check-label" for="mpesaRadio">M-Pesa</label> &nbsp;&nbsp;&nbsp;
                                                <img src="{% static 'svg/M-PESA.png' %}" alt="m-pesa"
                                                     style="height: 20px;">
                                            </div>
                                            <div class="form-check mt-2 d-flex align-items-center">
                                                <input type="radio" class="form-check-input" name="paymentMethod"
                                                       id="creditCardRadio" value="Credit/debit card">&nbsp;&nbsp;
                                                <label class="form-check-label" for="creditCardRadio">Credit/Debit
                                                    Card</label> &nbsp;
                                                <img src="{% static 'svg/visa-svgrepo-com.svg' %}" alt=""
                                                     style="height: 40px ;">
                                            </div>
                                        </div>
                                    </div>
                                    <br><br>
                                    <div class="d-flex justify-content-end">
                                        <button type="submit" href="" class="btn btn-outline-success">Confirm details</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <hr style="margin: 5px 0 15px 0;">
                </div>
            </div>

            <!-- Right Section: Order Summary -->
            <div class="container p-2 col-md-3 col-11 order-md-2 order-1 h-50"
                 style="background-color: white; box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                <h5 class="lead fs-6">Order Summary:</h5>
                <hr style="margin: 10px 0 10px 0;">
                <div class="d-flex justify-content-between pe-3">
                    <h6 class="">Item's total</h6>
                    <h6><strong>Ksh. {{ cost|format_number }}</strong></h6>
                </div>
                <div class="d-flex justify-content-between pe-3">
                    <h6 class="">Delivery Fees</h6>
                    <h6><strong>Ksh. {{ cost|format_number }}</strong></h6>
                </div>
                <hr style="margin: 10px 0 10px 0;">
                <div class="d-flex justify-content-between pe-3">
                    <h6 class="">Total:</h6>
                    <h6><strong>Ksh. {{ cost|format_number }}</strong></h6>
                </div>
                <hr style="margin: 10px 0 10px 0;">
                <div class="d-flex justify-content-center">
                    <button class="btn btn-secondary text-center w-100" disabled>
                        Confirm Order
                    </button>
                </div>
            </div>
        </div>


    </div>
    <script>
        function validateForm(){
            const paymentDate = document.querySelector('input[name="paymentDate"]:checked');
            const paymentMethod = document.querySelector('input[name="paymentMethod"]:checked');
            
            if (!paymentDate || !paymentMethod){
                alert("Please selecta a payment date and a payment method!");
                return false;
            }
            
            return true;
            
        }
        
    </script>
{% endblock %}

templates/order/checkout.html
{% extends 'common/base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}
    Checkout Summary | Barendo Systems
{% endblock %}
{% block content %}


    <div style="background-color: #f4f4f4">
        <br>
        <div class="row mx-3 mx-sm-4 mx-md-5 pb-4">
            <div class="container col-md-8 col-12 order-md-1 order-2 mt-4 mt-md-0">
                <div class="container w-100 shadowed-div"
                     style="margin-inline-end: 1%; background-color: white; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                    <div class="pt-3 ps-3 d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            {% if profile_complete %}
                                <i class="bi bi-check-circle-fill" style="color: green; margin-right: 8px;"></i>
                            {% else %}
                                <i class="bi bi-x-circle-fill"></i>
                            {% endif %}
                            <h6 class="mb-0">1. Customer Address</h6>
                        </div>
                        <a href="{% url 'order:update_address' %}" class="text-decoration-none" style="color: #3bc9fd">Change
                            ></a>
                    </div>
                    <hr style="margin: 2px 0 5px 0;">
                    <div class="row px-2 align-items-center">
                        <div class="p-2 ps-3">
                            <p>{{ user.first_name }} {{ user.first_name }} ({{ user.username }})</p>
                            {% if profile_complete %}
                                <p class="mt-1">{{ profile.phone }} | {{ user.email }}
                                    | {{ profile.address }}-{{ profile.zipcode }} - {{ profile.town }}</p>
                            {% else %}
                                <p class="mt-1">Complete your Profile</p>
                            {% endif %}
                        </div>
                    </div>
                    <hr style="margin: 5px 0 15px 0;">
                </div>

                <!-- Customer Address Block 2 -->
                <div class="container w-100 shadowed-div"
                     style="margin-inline-end: 1%; background-color: white; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                    <div class="pt-3 ps-3 d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="bi bi-check-circle-fill" style="color: green; margin-right: 8px;"></i>
                            <h6 class="mb-0">2. Delivery Details</h6>
                        </div>
                    </div>
                    <hr style="margin: 2px 0 5px 0;">
                    <div class="row px-2 align-items-center">
                        <div class="p-2 d-flex align-items-center">
                            <h6 class="mb-0">Delivered to {{ profile.town }} </h6> &nbsp;&nbsp;
                            <p class="mb-0">from(Ksh. 600)</p>
                        </div>
                        <div class="">
                            <p style="font-weight: 300">Delivery between <strong>13 November</strong> and <strong>18
                                November</strong></p>
                        </div>
                        <div class="row">
                            {% for product in products %}
                                <div class="col-12 col-md-6">
                                    <div class="d-flex justify-content-start">
                                        <p class="mb-0" style="font-weight: 200; font-size: 10px;">
                                            Shipment {{ forloop.counter }}/{{ cart|length }}</p>
                                    </div>
                                    <div style="border: 0.5px, solid, #b6b6b6; border-radius: 5px" class="p-2 mb-2 ">
                                        <p class="mb-0" style="font-weight: 300; font-size: 11px;">Delivery between
                                            <strong>13 November</strong> and
                                            <strong>18 November</strong></p>
                                        <hr style="margin: 1px;">
                                        <div class="d-flex mt-2 align-items-center">
                                            <img style="height: 50px; width:auto;"
                                                 src="{{ product.primary_image.url }}" alt="">
                                            <div class="d-block ms-4">
                                                <p class="mb-0" style="font-weight: 200">{{ product.product_name }}</p>

                                                {% for key, value in cart.items %}
                                                    {% if key == product.id|slugify %}
                                                        <p style="font-weight: 200">QTY: {{ value.quantity }}</p>
                                                    {% endif %}
                                                {% endfor %}

                                            </div>

                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                        <div class="d-flex justify-content-center my-3">
                            <a href="{% url 'cart:cart_home' %}" class="text-decoration-none text-success">MODIFY
                                CART</a>
                        </div>
                    </div>
                    <hr style="margin: 5px 0 15px 0;">
                </div>

                <!-- Customer Address Block 3 -->
                <div class="container w-100 shadowed-div"
                     style="margin-inline-end: 1%; background-color: white; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                    <div class="pt-3 ps-3 d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="bi bi-check-circle-fill" style="color: green; margin-right: 8px;"></i>
                            <h6 class="mb-0">3. Payment Details</h6>
                        </div>
                        <a href="{% url 'order:update_payment_details' %}" class="text-decoration-none"
                           style="color: #3bc9fd">Change ></a>
                    </div>
                    <hr style="margin: 2px 0 5px 0;">
                    <div class="row px-2 align-items-center">
                        <div class="payment-options p-3 rounded" style="">
                            {% if payment_complete %}
                                <h6>{{ paymentDate }} | {{ paymentMethod }}</h6>
                            {% else %}
                                <h6>Add your payment details</h6>
                            {% endif %}
                        </div>
                    </div>
                    <hr style="margin: 5px 0 15px 0;">
                </div>
            </div>

            <!-- Right Section: Order Summary -->
            <div class="container p-2 col-md-3 col-11 order-md-2 order-1 h-50"
                 style="background-color: white; box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.2); border-radius: 5px;">
                <h5 class="lead fs-6">Order Summary:</h5>
                <hr style="margin: 10px 0 10px 0;">
                <div class="d-flex justify-content-between pe-3">
                    <h6>Item's total</h6>
                    <h6 id="products_cost"><strong>Ksh. {{ products_cost|format_number }}</strong></h6>
                </div>
                <div class="d-flex justify-content-between pe-3">
                    <h6>Delivery Fees</h6>
                    <h6 id="delivery_cost"><strong>Ksh. 600</strong></h6>
                </div>
                <hr style="margin: 10px 0 10px 0;">
                <div class="d-flex justify-content-between pe-3">
                    <h6>Total:</h6>
                    <h6 id="total_cost"><strong>Ksh. 0</strong></h6> <!-- Initial value set to 0 -->
                </div>

                <div class="d-flex justify-content-center">
                    {% if profile_complete and payment_complete %}
                        <a href="{% url 'order:payment_processing' %}" class="btn btn-secondary text-center w-100">
                            Confirm Order
                        </a>
                    {% else %}
                        <a href="" class="disabled btn btn-secondary text-center w-100">
                            Confirm Order
                        </a>
                    {% endif %}
                    
                </div>
            </div>
        </div>


    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Select elements
            const productsCostElement = document.getElementById("products_cost");
            const deliveryCostElement = document.getElementById("delivery_cost");
            const totalCostElement = document.getElementById("total_cost");

            // Extract the numbers, assuming the format "Ksh. 12345"
            const productsCost = parseFloat(productsCostElement.innerText.replace("Ksh. ", "").replace(",", ""));
            const deliveryCost = parseFloat(deliveryCostElement.innerText.replace("Ksh. ", "").replace(",", ""));

            // Calculate the total cost
            const totalCost = productsCost + deliveryCost;

            // Display the total cost in the "Total" section
            totalCostElement.innerHTML = `<strong>Ksh. ${totalCost.toLocaleString()}</strong>`;
        });
    </script>


{% endblock %}

templates/order/order.html
{% extends 'common/base.html' %}
{% load static %}

{% block title %}
    Orders | Pre-paid
{% endblock %}

{% block content %}
{% include 'common/navigation.html' %}
    <div class="col-12 mx-auto text-center my-1">
        <h2><u>Order by {{order.user}}</u></h5>
    </div>
    <div class="col-10 col-md-8 p-3 mx-auto justify-content-start row" style="background-color: #e8f7ec;">
        <div class="col-12 col-md-6">
            <h4><u>User</u>:</h4>
            <p>Username: {{order.user.username}}</p>
            <p>Name: {{order.user.first_name}} {{order.user.last_name}}</p>
            <p>Email: {{order.user.email}}</p>
            <p>Phone: {{order.phone}}</p>
        </div>
        <div class="col-12 col-md-6">
            <h4><u>Products</u>:</h4>
            {% for item in order_items %}
                <h6><strong>{{item.product.product_name}}</strong></h6>
                <p>Quantity: {{item.quantity}}</p>
                <p>Price: Ksh. {{item.price}}</p>
            {% endfor %}
        </div>
        <div class="col-12 col-md-6 mx-auto">
            <div class="d-flex justify-content-between">
                <form action="{% url 'order:specific-order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">
                        Shipped
                    </button>
                </form>
                
                <form action="{% url 'order:cancel-order' order.id %}" method="post">
                    {% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit">
                            Cancel Order
                        </button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}